name: flutter_map_location
description: flutter_map plugin to request and display the users location and heading on the map.
version: 0.12.0
homepage: https://github.com/Xennis/flutter_map_location

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
